### ISSUE TITLE
[ISSUE][this package itself specifies a `main` module field that could not be resolved]

### ISSUE THREAD

**Issue by michaelanggriawan** [Qiscus-Integration/react-native-multichannel-widget#14]
`this package itself specifies a `main` module field that could not be resolved` 

I was trying to install this package into my project, and currently, I was facing the above issue, I think there's an issue inside this package that needs to be updated.

![Screenshot 2022-11-29 at 14 13 32](https://user-images.githubusercontent.com/37749891/204474507-a0b6c9a1-494c-4acc-bf94-c192bf20865a.png)

![Screenshot_20221129-150452_qiscus (1)](https://user-images.githubusercontent.com/37749891/204474739-a817e622-2ce7-4213-9259-e37d6d41595f.jpg)

**Comment by tfkbudi** [comment]
there is an issue in our SDK package, this has been fixed by our team. please clean install and let us know if the problem still exists. thank you
